/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dossier;
import java.awt.Dimension;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Osmani Alegre
 */
public class AdminDemo extends javax.swing.JFrame {

    /** Creates new form Demo */
    ArrayList<JCheckBox> bArray = new ArrayList();
    
    String username = System.getProperty("user.name");
    String path = "C:/Users/"+username+"/Documents/PollAway/demo/demo.txt";
    File file = new File(path);
    
    public AdminDemo() {
        initComponents();
        this.revalidate();
        readDemoFile();
        displayBox();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DemoName = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        dName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DemoPanel = new javax.swing.JPanel();
        DeleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        contButton = new javax.swing.JButton();

        DemoName.setResizable(false);

        jLabel2.setText("Name of Demographic:");

        dName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNameActionPerformed(evt);
            }
        });

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DemoNameLayout = new javax.swing.GroupLayout(DemoName.getContentPane());
        DemoName.getContentPane().setLayout(DemoNameLayout);
        DemoNameLayout.setHorizontalGroup(
            DemoNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoNameLayout.createSequentialGroup()
                .addGroup(DemoNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemoNameLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(dName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DemoNameLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DemoNameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        DemoNameLayout.setVerticalGroup(
            DemoNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoNameLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(dName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Current Demographics:");

        javax.swing.GroupLayout DemoPanelLayout = new javax.swing.GroupLayout(DemoPanel);
        DemoPanel.setLayout(DemoPanelLayout);
        DemoPanelLayout.setHorizontalGroup(
            DemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        DemoPanelLayout.setVerticalGroup(
            DemoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        contButton.setText("Continue");
        contButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DemoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(contButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DeleteButton)
                        .addGap(63, 63, 63)
                        .addComponent(addButton)
                        .addGap(62, 62, 62)
                        .addComponent(contButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DemoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButtonActionPerformed
        AdminAddPoll a = new AdminAddPoll();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_contButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        ArrayList<JCheckBox> temp = new ArrayList();
        
        for (int i = 0; i < bArray.size(); i++) {
            if (bArray.get(i).isSelected()) {
                    temp.add(bArray.get(i));
            }
        }
        
        for (int i = 0; i < temp.size(); i++) {
            for (int j = 0; j < bArray.size(); j++) {
                if (temp.get(i).getText().equals(bArray.get(j).getText())) {
                    bArray.remove(i);
                }
            }
        }
        
        
        try {
            writeDemoFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayBox();
        this.revalidate();
        
        
        for (int i = 0; i < bArray.size(); i++) {
            System.out.print(bArray.get(i).getText() + ",");
        }
        
        System.out.println("**");
        
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Dimension n = new Dimension(400, 300);
        DemoName.setSize(n);
        DemoName.setVisible(true);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void dNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JCheckBox e = new JCheckBox();
        e.setText(dName.getText());
        bArray.add(e);
        DemoName.setVisible(false);
        try {
            writeDemoFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminDemo.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayBox();
        this.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void writeDemoFile() throws FileNotFoundException{
        PrintWriter writer = new PrintWriter(file);
        writer.print("");
        writer.close();
        
        PrintWriter w = new PrintWriter(file);
        for (int i = 0; i < bArray.size(); i++) {
            w.println(bArray.get(i).getText());
        }
        w.close();
        
    }
    
    private void readDemoFile(){
        
        try {
            File file = new File(path);
            Scanner s = new Scanner(new BufferedReader(new FileReader(path)));

            while (s.hasNextLine()) {
                String line = s.nextLine();
                JCheckBox e = new JCheckBox();
                e.setText(line);
                bArray.add(e);
            }
            s.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        } 
    }
    
    
    
    private void displayBox(){
        DemoPanel.removeAll();
        for (int i = 0; i < bArray.size(); i++) {
            if (bArray.get(i).getText().charAt(0) == '*') {
                JLabel j = new JLabel();
                j.setText(bArray.get(i).getText().substring(1));
                DemoPanel.add(j);
            }
            else{
                DemoPanel.add(bArray.get(i));
                DemoPanel.setLayout(new BoxLayout(DemoPanel, BoxLayout.Y_AXIS));
            }
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JDialog DemoName;
    private javax.swing.JPanel DemoPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton contButton;
    private javax.swing.JTextField dName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
